// Natural Earth 10m populated places simple; selected by city AND country.
// Ambiguous English city names require a country qualifier. See docs/geolocation.md.
export const globalPlaces = [
  {
    name: '纽约，美国',
    country: '美国',
    parent: null,
    lat: 40.721562,
    lng: -73.995718,
    precision: 'city',
    aliases: ['纽约', 'New York City'],
  },
  {
    name: '芝加哥，美国',
    country: '美国',
    parent: null,
    lat: 41.847961,
    lng: -87.635237,
    precision: 'city',
    aliases: ['芝加哥', 'Chicago'],
  },
  {
    name: '波士顿，美国',
    country: '美国',
    parent: null,
    lat: 42.331906,
    lng: -71.07196,
    precision: 'city',
    aliases: ['波士顿', 'Boston'],
  },
  {
    name: '迈阿密，美国',
    country: '美国',
    parent: '佛罗里达州，美国',
    lat: 25.789557,
    lng: -80.226052,
    precision: 'city',
    aliases: ['迈阿密', 'Miami'],
  },
  {
    name: '休斯敦，美国',
    country: '美国',
    parent: '得克萨斯州，美国',
    lat: 29.741273,
    lng: -95.348436,
    precision: 'city',
    aliases: ['休斯敦', 'Houston', '休斯顿'],
  },
  {
    name: '西雅图，美国',
    country: '美国',
    parent: null,
    lat: 47.600423,
    lng: -122.315322,
    precision: 'city',
    aliases: ['西雅图', 'Seattle'],
  },
  {
    name: '檀香山，美国',
    country: '美国',
    parent: '夏威夷州，美国',
    lat: 21.303429,
    lng: -157.858301,
    precision: 'city',
    aliases: ['檀香山', 'Honolulu'],
  },
  {
    name: '温哥华，加拿大',
    country: '加拿大',
    parent: '不列颠哥伦比亚，加拿大',
    lat: 49.275362,
    lng: -123.12359,
    precision: 'city',
    aliases: ['温哥华', 'Vancouver, Canada'],
  },
  {
    name: '渥太华，加拿大',
    country: '加拿大',
    parent: '安大略省，加拿大',
    lat: 45.418643,
    lng: -75.701961,
    precision: 'city',
    aliases: ['渥太华', 'Ottawa'],
  },
  {
    name: '墨西哥城，墨西哥',
    country: '墨西哥',
    parent: null,
    lat: 19.444388,
    lng: -99.132934,
    precision: 'city',
    aliases: ['墨西哥城', 'Mexico City'],
  },
  {
    name: '波哥大，哥伦比亚',
    country: '哥伦比亚',
    parent: null,
    lat: 4.598369,
    lng: -74.08529,
    precision: 'city',
    aliases: ['波哥大', 'Bogota'],
  },
  {
    name: '基多，厄瓜多尔',
    country: '厄瓜多尔',
    parent: null,
    lat: -0.213042,
    lng: -78.501997,
    precision: 'city',
    aliases: ['基多', 'Quito'],
  },
  {
    name: '利马，秘鲁',
    country: '秘鲁',
    parent: null,
    lat: -12.046067,
    lng: -77.052008,
    precision: 'city',
    aliases: ['利马', 'Lima, Peru'],
  },
  {
    name: '里约热内卢，巴西',
    country: '巴西',
    parent: null,
    lat: -22.907308,
    lng: -43.212117,
    precision: 'city',
    aliases: ['里约热内卢', 'Rio de Janeiro'],
  },
  {
    name: '布宜诺斯艾利斯，阿根廷',
    country: '阿根廷',
    parent: null,
    lat: -34.610715,
    lng: -58.432513,
    precision: 'city',
    aliases: ['布宜诺斯艾利斯', 'Buenos Aires'],
  },
  {
    name: '圣地亚哥，智利',
    country: '智利',
    parent: null,
    lat: -33.440205,
    lng: -70.650504,
    precision: 'city',
    aliases: ['圣地亚哥', 'Santiago, Chile', '智利圣地亚哥'],
  },
  {
    name: '墨尔本，澳大利亚',
    country: '澳大利亚',
    parent: '维多利亚州，澳大利亚',
    lat: -37.818086,
    lng: 144.97307,
    precision: 'city',
    aliases: ['墨尔本', 'Melbourne, Australia'],
  },
  {
    name: '布里斯班，澳大利亚',
    country: '澳大利亚',
    parent: '昆士兰州，澳大利亚',
    lat: -27.453085,
    lng: 153.033147,
    precision: 'city',
    aliases: ['布里斯班', 'Brisbane'],
  },
  {
    name: '珀斯，澳大利亚',
    country: '澳大利亚',
    parent: null,
    lat: -31.953069,
    lng: 115.838053,
    precision: 'city',
    aliases: ['珀斯', 'Perth, Australia'],
  },
  {
    name: '阿德莱德，澳大利亚',
    country: '澳大利亚',
    parent: null,
    lat: -34.933042,
    lng: 138.598059,
    precision: 'city',
    aliases: ['阿德莱德', 'Adelaide'],
  },
  {
    name: '堪培拉，澳大利亚',
    country: '澳大利亚',
    parent: null,
    lat: -35.283029,
    lng: 149.129026,
    precision: 'city',
    aliases: ['堪培拉', 'Canberra'],
  },
  {
    name: '奥克兰，新西兰',
    country: '新西兰',
    parent: null,
    lat: -36.848055,
    lng: 174.763027,
    precision: 'city',
    aliases: ['奥克兰', 'Auckland'],
  },
  {
    name: '惠灵顿，新西兰',
    country: '新西兰',
    parent: null,
    lat: -41.292068,
    lng: 174.777201,
    precision: 'city',
    aliases: ['惠灵顿', 'Wellington'],
  },
] as const
