// Representative points from Natural Earth 5.1.1 admin-1 and 5.1.2 populated places.
// See docs/geolocation.md for sources and matching limitations.
import { globalPlaces } from './globalPlaces'
export const placeCatalog = [
  // Approximate representative points, not article-specific incident coordinates.
  {
    name: '圣安东尼奥，得克萨斯州，美国',
    country: '美国',
    parent: '得克萨斯州，美国',
    lat: 29.42,
    lng: -98.49,
    precision: 'city',
    aliases: ['圣安东尼奥', 'San Antonio'],
  },
  {
    name: '霍尔木兹海峡',
    country: '霍尔木兹海峡',
    parent: null,
    lat: 26.6,
    lng: 56.5,
    precision: 'region',
    aliases: ['霍尔木兹海峡', 'Strait of Hormuz'],
  },
  {
    name: '昆明，云南省，中国',
    country: '中国',
    parent: '云南省，中国',
    lat: 25.04,
    lng: 102.71,
    precision: 'city',
    aliases: ['昆明', 'Kunming'],
  },
  {
    name: '海口，海南省，中国',
    country: '中国',
    parent: '海南省，中国',
    lat: 20.04,
    lng: 110.34,
    precision: 'city',
    aliases: ['海口', 'Haikou'],
  },
  {
    name: '重庆，中国',
    country: '中国',
    parent: null,
    lat: 29.56,
    lng: 106.55,
    precision: 'city',
    aliases: ['重庆', 'Chongqing'],
  },
  {
    name: '金边，柬埔寨',
    country: '柬埔寨',
    parent: null,
    lat: 11.56,
    lng: 104.92,
    precision: 'city',
    aliases: ['金边', 'Phnom Penh'],
  },
  {
    name: '香港，中国',
    country: '中国',
    parent: null,
    lat: 22.3,
    lng: 114.17,
    precision: 'city',
    aliases: ['香港', 'Hong Kong'],
  },
  ...globalPlaces,
  {
    name: '成都，四川省，中国',
    country: '中国',
    parent: '四川省，中国',
    lat: 30.6719,
    lng: 104.0681,
    precision: 'city',
    aliases: ['成都', 'Chengdu'],
  },
  {
    name: '深圳，广东省，中国',
    country: '中国',
    parent: '广东省，中国',
    lat: 22.5543,
    lng: 114.1202,
    precision: 'city',
    aliases: ['深圳', 'Shenzhen'],
  },
  {
    name: '广州，广东省，中国',
    country: '中国',
    parent: '广东省，中国',
    lat: 23.1469,
    lng: 113.3231,
    precision: 'city',
    aliases: ['广州', 'Guangzhou'],
  },
  {
    name: '旧金山，加利福尼亚州，美国',
    country: '美国',
    parent: '加利福尼亚州，美国',
    lat: 37.7692,
    lng: -122.4172,
    precision: 'city',
    aliases: ['旧金山', 'San Francisco'],
  },
  {
    name: '多伦多，安大略省，加拿大',
    country: '加拿大',
    parent: '安大略省，加拿大',
    lat: 43.7019,
    lng: -79.422,
    precision: 'city',
    aliases: ['多伦多', 'Toronto'],
  },
  {
    name: '悉尼，新南威尔士州，澳大利亚',
    country: '澳大利亚',
    parent: '新南威尔士州，澳大利亚',
    lat: -33.9181,
    lng: 151.1832,
    precision: 'city',
    aliases: ['悉尼', 'Sydney'],
  },
  {
    name: '慕尼黑，巴伐利亚州，德国',
    country: '德国',
    parent: '巴伐利亚州，德国',
    lat: 48.1319,
    lng: 11.573,
    precision: 'city',
    aliases: ['慕尼黑', 'Munich'],
  },
  {
    name: '柏林，德国',
    country: '德国',
    parent: null,
    lat: 52.5238,
    lng: 13.3996,
    precision: 'city',
    aliases: ['柏林', 'Berlin'],
  },
  {
    name: '上海，中国',
    country: '中国',
    parent: null,
    lat: 31.2184,
    lng: 121.4346,
    precision: 'city',
    aliases: ['上海', 'Shanghai'],
  },
  {
    name: '北京，中国',
    country: '中国',
    parent: null,
    lat: 39.9308,
    lng: 116.3863,
    precision: 'city',
    aliases: ['北京', 'Beijing'],
  },
  {
    name: '东京，日本',
    country: '日本',
    parent: null,
    lat: 35.687,
    lng: 139.7495,
    precision: 'city',
    aliases: ['东京', 'Tokyo'],
  },
  {
    name: '名古屋，爱知县，日本',
    country: '日本',
    parent: '爱知县，日本',
    lat: 35.1569,
    lng: 136.913,
    precision: 'city',
    aliases: ['名古屋', 'Nagoya'],
  },
  {
    name: '麦加，麦加省，沙特阿拉伯',
    country: '沙特阿拉伯',
    parent: '麦加省，沙特阿拉伯',
    lat: 21.432,
    lng: 39.8181,
    precision: 'city',
    aliases: ['麦加', 'Makkah', 'Mecca'],
  },
  {
    name: '约翰内斯堡，豪登省，南非',
    country: '南非',
    parent: '豪登省，南非',
    lat: -26.1681,
    lng: 28.0281,
    precision: 'city',
    aliases: ['约翰内斯堡', 'Johannesburg'],
  },
  {
    name: '洛杉矶，加利福尼亚州，美国',
    country: '美国',
    parent: '加利福尼亚州，美国',
    lat: 33.9919,
    lng: -118.1819,
    precision: 'city',
    aliases: ['洛杉矶', 'Los Angeles'],
  },
  {
    name: '萨克森州，德国',
    country: '德国',
    parent: null,
    lat: 51.0053,
    lng: 13.4596,
    precision: 'region',
    aliases: ['萨克森州', 'Saxony'],
  },
  {
    name: '巴伐利亚州，德国',
    country: '德国',
    parent: null,
    lat: 49.0056,
    lng: 11.3966,
    precision: 'region',
    aliases: ['巴伐利亚州', 'Bavaria'],
  },
  {
    name: '云南省，中国',
    country: '中国',
    parent: null,
    lat: 24.4603,
    lng: 101.661,
    precision: 'region',
    aliases: ['云南省', '云南', 'Yunnan'],
  },
  {
    name: '勃兰登堡州，德国',
    country: '德国',
    parent: null,
    lat: 52.8156,
    lng: 12.9206,
    precision: 'region',
    aliases: ['勃兰登堡州', 'Brandenburg'],
  },
  {
    name: '不列颠哥伦比亚，加拿大',
    country: '加拿大',
    parent: null,
    lat: 54.6943,
    lng: -124.662,
    precision: 'region',
    aliases: ['不列颠哥伦比亚', 'British Columbia'],
  },
  {
    name: '安大略省，加拿大',
    country: '加拿大',
    parent: null,
    lat: 50.5244,
    lng: -84.7943,
    precision: 'region',
    aliases: ['安大略省', 'Ontario'],
  },
  {
    name: '俄亥俄州，美国',
    country: '美国',
    parent: null,
    lat: 40.0924,
    lng: -82.6719,
    precision: 'region',
    aliases: ['俄亥俄州', 'Ohio'],
  },
  {
    name: '宾夕法尼亚州，美国',
    country: '美国',
    parent: null,
    lat: 40.8601,
    lng: -77.6094,
    precision: 'region',
    aliases: ['宾夕法尼亚州', 'Pennsylvania'],
  },
  {
    name: '魁北克，加拿大',
    country: '加拿大',
    parent: null,
    lat: 52.2593,
    lng: -73.7168,
    precision: 'region',
    aliases: ['魁北克', 'Quebec'],
  },
  {
    name: '加利福尼亚州，美国',
    country: '美国',
    parent: null,
    lat: 36.7496,
    lng: -119.591,
    precision: 'region',
    aliases: ['加利福尼亚州', 'California'],
  },
  {
    name: '新墨西哥州，美国',
    country: '美国',
    parent: null,
    lat: 34.5002,
    lng: -106.024,
    precision: 'region',
    aliases: ['新墨西哥州', 'New Mexico'],
  },
  {
    name: '得克萨斯州，美国',
    country: '美国',
    parent: null,
    lat: 31.131,
    lng: -98.7607,
    precision: 'region',
    aliases: ['得克萨斯州', 'Texas'],
  },
  {
    name: '阿拉斯加州，美国',
    country: '美国',
    parent: null,
    lat: 65.3609,
    lng: -151.604,
    precision: 'region',
    aliases: ['阿拉斯加州', 'Alaska'],
  },
  {
    name: '广东省，中国',
    country: '中国',
    parent: null,
    lat: 23.7924,
    lng: 113.72,
    precision: 'region',
    aliases: ['广东省', '广东', 'Guangdong'],
  },
  {
    name: '昆士兰州，澳大利亚',
    country: '澳大利亚',
    parent: null,
    lat: -23.1364,
    lng: 144.778,
    precision: 'region',
    aliases: ['昆士兰州', 'Queensland'],
  },
  {
    name: '新南威尔士州，澳大利亚',
    country: '澳大利亚',
    parent: null,
    lat: -32.4751,
    lng: 146.781,
    precision: 'region',
    aliases: ['新南威尔士州', 'New South Wales'],
  },
  {
    name: '维多利亚州，澳大利亚',
    country: '澳大利亚',
    parent: null,
    lat: -37.0082,
    lng: 144.75,
    precision: 'region',
    aliases: ['维多利亚州', 'Victoria State', 'Victoria Province'],
  },
  {
    name: '福建省，中国',
    country: '中国',
    parent: null,
    lat: 26.408,
    lng: 118.178,
    precision: 'region',
    aliases: ['福建省', '福建', 'Fujian'],
  },
  {
    name: '麦加省，沙特阿拉伯',
    country: '沙特阿拉伯',
    parent: null,
    lat: 21.4348,
    lng: 40.2542,
    precision: 'region',
    aliases: ['麦加省', 'Makkah Province', 'Mecca Province'],
  },
  {
    name: '亚拉巴马州，美国',
    country: '美国',
    parent: null,
    lat: 32.8551,
    lng: -86.7184,
    precision: 'region',
    aliases: ['亚拉巴马州', 'Alabama'],
  },
  {
    name: '佛罗里达州，美国',
    country: '美国',
    parent: null,
    lat: 28.1568,
    lng: -81.6228,
    precision: 'region',
    aliases: ['佛罗里达州', 'Florida'],
  },
  {
    name: '浙江省，中国',
    country: '中国',
    parent: null,
    lat: 29.1084,
    lng: 119.97,
    precision: 'region',
    aliases: ['浙江省', '浙江', 'Zhejiang'],
  },
  {
    name: '江苏省，中国',
    country: '中国',
    parent: null,
    lat: 32.9844,
    lng: 119.942,
    precision: 'region',
    aliases: ['江苏省', '江苏', 'Jiangsu'],
  },
  {
    name: '山东省，中国',
    country: '中国',
    parent: null,
    lat: 36.3271,
    lng: 118.114,
    precision: 'region',
    aliases: ['山东省', '山东', 'Shandong'],
  },
  {
    name: '河北省，中国',
    country: '中国',
    parent: null,
    lat: 38.5205,
    lng: 115.314,
    precision: 'region',
    aliases: ['河北省', '河北', 'Hebei'],
  },
  {
    name: '夏威夷州，美国',
    country: '美国',
    parent: null,
    lat: 21.4919,
    lng: -157.999,
    precision: 'region',
    aliases: ['夏威夷州', 'Hawaii'],
  },
  {
    name: '内华达州，美国',
    country: '美国',
    parent: null,
    lat: 39.4299,
    lng: -117.02,
    precision: 'region',
    aliases: ['内华达州', 'Nevada'],
  },
  {
    name: '豪登省，南非',
    country: '南非',
    parent: null,
    lat: -26.1682,
    lng: 28.2074,
    precision: 'region',
    aliases: ['豪登省', 'Gauteng'],
  },
  {
    name: '四川省，中国',
    country: '中国',
    parent: null,
    lat: 30.5431,
    lng: 102.384,
    precision: 'region',
    aliases: ['四川省', '四川', 'Sichuan'],
  },
  {
    name: '湖南省，中国',
    country: '中国',
    parent: null,
    lat: 27.6667,
    lng: 111.712,
    precision: 'region',
    aliases: ['湖南省', '湖南', 'Hunan'],
  },
  {
    name: '陕西省，中国',
    country: '中国',
    parent: null,
    lat: 33.7713,
    lng: 108.363,
    precision: 'region',
    aliases: ['陕西省', '陕西', 'Shaanxi'],
  },
  {
    name: '山西省，中国',
    country: '中国',
    parent: null,
    lat: 37.7586,
    lng: 112.389,
    precision: 'region',
    aliases: ['山西省', '山西', 'Shanxi'],
  },
  {
    name: '江西省，中国',
    country: '中国',
    parent: null,
    lat: 27.6397,
    lng: 116.017,
    precision: 'region',
    aliases: ['江西省', '江西', 'Jiangxi'],
  },
  {
    name: '河南省，中国',
    country: '中国',
    parent: null,
    lat: 33.9055,
    lng: 113.484,
    precision: 'region',
    aliases: ['河南省', '河南', 'Henan'],
  },
  {
    name: '湖北省，中国',
    country: '中国',
    parent: null,
    lat: 30.9857,
    lng: 112.264,
    precision: 'region',
    aliases: ['湖北省', '湖北', 'Hubei'],
  },
  {
    name: '安徽省，中国',
    country: '中国',
    parent: null,
    lat: 31.9537,
    lng: 117.253,
    precision: 'region',
    aliases: ['安徽省', '安徽', 'Anhui'],
  },
] as const
